#  menu items

[[main]]
	name = "Home"
	weight = 10
	url = "./"

[[main]]
  name = "Docs"
  weight = 20
  url = "/docs/treant"

[[main]]
  name = "Changelog"
  weight = 30
  url = "changelog/"

[[main]]
	name = "Blog"
	weight = 40
	url = "blog/"

[[main]]
	name = "Login"
	weight = 50
	url = "https://aquiles-test.treant.io"