#  menu items
[[main]]
  name = "Docs"
  weight = 1
  #url = "docs/"

[[main]]
  name = "Tutorials"
  weight = 2
  #url = "tutorials/"


[[main]]
	name = "Blog"
	weight = 3
	#url = "blog/"

[[main]]
	name = "Login"
	weight = 4
	url = "https://aquiles-test.treant.io"