#  menu items
[[main]]
  name = "Docs"
  weight = 10
  url = "docs/treant"

[[main]]
  name = "Changelog"
  weight = 20
  url = "changelog/"


[[main]]
	name = "Blog"
	weight = 30
	url = "blog/"

[[main]]
	name = "Start"
	weight = 40
	url = "signup/"

[[main]]
	name = "Login"
	weight = 50
	url = "https://aquiles-test.treant.io"