baseURL = 'https://treant.io/'
languageCode = 'en-us'
title = 'Treant Site'
theme = "compose"

[outputs]
   home = ["HTML", "RSS","JSON"]

[params]
	mainSections = ["docs", "blog"]
	

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    
    title = "Treant Site"
    languageName = "English"
    weight = 1
  [languages.es]
  
    title = "Sitio de Treant"
    languageName = "Español"
    weight = 2

defaultContentLanguageInSubdir = true