mainSections = ["posts"] # use it for blog page section
# use the setting below to set multiple docs directories.
# docSections = ["docs", "tutorials"]

uniqueHomePage = true # change to false to add sidebar to homepage
sidebar = false
repo = "https://github.com/treant-io"
enableSearch = false
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
enableDarkMode = true # set to false to disable darkmode by default # user will still have the option to use dark mode

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 7

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = false

# By default the template will look for icons under the icons directory. In some situations you might wanna change that. edit the line below
# iconsPath = 'icons/'

# Site logo
[logo]
  lightMode = "https://treantrepositories.blob.core.windows.net/www/opcion-1-azul.svg?sp=r&st=2021-08-13T19:40:29Z&se=2029-08-14T03:40:29Z&spr=https&sv=2020-08-04&sr=b&sig=RnxD9Fa5ydo6VZwGoSBHQQWMRstCoXM6THH3NvZUkSM%3D"
  darkMode = "https://treantrepositories.blob.core.windows.net/www/opcion-1-azul.svg?sp=r&st=2021-08-13T19:40:29Z&se=2029-08-14T03:40:29Z&spr=https&sv=2020-08-04&sr=b&sig=RnxD9Fa5ydo6VZwGoSBHQQWMRstCoXM6THH3NvZUkSM%3D"

[source]
  name = "GitHub"
  iconLight = "images/GitHubMarkLight.svg"
  iconDark = "images/GitHubMarkDark.svg"
  url = "https://github.com/treant-io"

# optional
# attribution. Feel free to delete this
[author]
  name = "Treant"
  url = "https://treant.io"
